<a href="https://colab.research.google.com/github/matchbou/Public/blob/master/scikit-learn%20%E3%81%AE%E3%83%AD%E3%82%B8%E3%82%B9%E3%83%86%E3%82%A3%E3%83%83%E3%82%AF%E5%9B%9E%E5%B8%B0%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%A6%E3%81%BF%E3%82%8B20190709aa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#Python: scikit-learn のロジスティック回帰を使ってみる

# https://blog.amedama.jp/entry/2018/08/26/095444

In [2]:
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_validate


def main():
    # 乳がんデータセットを読み込む
    dataset = datasets.load_breast_cancer()
    X, y = dataset.data, dataset.target

    # ロジスティック回帰
    clf = LogisticRegression()
    # Stratified K-Fold CV で性能を評価する
    skf = StratifiedKFold(shuffle=True)
    scoring = {
        'acc': 'accuracy',
        'auc': 'roc_auc',
    }
    scores = cross_validate(clf, X, y, cv=skf, scoring=scoring)

    print('Accuracy (mean):', scores['test_acc'].mean())
    print('AUC (mean):', scores['test_auc'].mean())


if __name__ == '__main__':
    main()

Accuracy (mean): 0.9420124385036664
AUC (mean): 0.9916462359591725


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:629: FutureWarning: The default value of n_split will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(NSPLIT_WARNING, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [3]:
from sklearn import datasets
dataset = datasets.load_breast_cancer()
dataset.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [4]:
len(dataset.feature_names)

30

In [5]:
import numpy as np
np.unique(y)

NameError: ignored

In [6]:
from sklearn.model_selection import train_test_split
X, y = dataset.data, dataset.target
X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle=True, random_state=42)
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(X_train, y_train)
LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
                   solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [7]:
clf.intercept_

array([0.3983173])

In [8]:
 clf.coef_

array([[ 2.15947495e+00,  1.51300435e-01, -1.51667529e-01,
        -1.04954508e-03, -1.26132897e-01, -4.16902786e-01,
        -6.37014042e-01, -3.30208767e-01, -1.93186305e-01,
        -3.16514087e-02, -6.42884594e-02,  1.46139805e+00,
         5.11452976e-02, -1.05030065e-01, -1.37419376e-02,
        -3.54734449e-02, -7.11797076e-02, -3.87287355e-02,
        -4.68343528e-02, -2.11718530e-03,  1.21925189e+00,
        -3.91905491e-01, -5.36269980e-02, -2.44826487e-02,
        -2.37531384e-01, -1.19307187e+00, -1.58468796e+00,
        -5.90013648e-01, -7.09548437e-01, -1.19718847e-01]])

In [9]:
len(clf.coef_[0])

30

In [10]:
clf.predict([X_test[0]])

array([1])

In [11]:
clf.predict_proba([X_test[0]])

array([[0.19112328, 0.80887672]])

In [12]:
y_test[0]

1

In [13]:
import numpy as np
y = np.sum(clf.coef_ * X_test[0]) + clf.intercept_
y

array([1.44272784])

In [0]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))


In [15]:
z = sigmoid(y)
z

array([0.80887672])